phpVersion: '8.2'
printWidth: 130
useTabs: true
tabWidth: 4
braceStyle: '1tbs'
trailingCommaPHP: true
singleQuote: true
plugins:
    - '@prettier/plugin-php'
    - '@shufo/prettier-plugin-blade'
overrides:
  - files: '*.blade.php'
    options:
      parser: 'blade'
      tabWidth: 1